name: Checkov
on:
  pull_request:
    types:
      - opened
  push:
    branches: ['*'] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
      - name: Post Checkov scan results to PR comments
        if: always()
        run: |
          # Read the Checkov scan results from the output file
          checkov_results=$(cat ${{ steps.checkov.outputs.checkovOutput }})

          # Create a comment on the pull request using the GitHub API
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"\`\`\`sarif\n$checkov_results\n\`\`\`\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
