name: Terraform Cleanup

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform Cleaner
        run: |
          wget https://github.com/sylwit/terraform-cleaner/releases/download/v0.0.4/terraform-cleaner_0.0.4_linux_amd64.tar.gz
          tar -xvf terraform-cleaner_0.0.4_linux_amd64.tar.gz

      - name: Run Terraform Cleaner
        run: |
           mv terraform-cleaner /usr/local/bin 
           terraform-cleaner
