name: Terraform Cleanup

on:
  pull_request:
    types:
      - opened

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform Cleaner
        run: |
          wget https://github.com/sylwit/terraform-cleaner/releases/download/v0.0.4/terraform-cleaner_0.0.4_linux_amd64.tar.gz
          tar -xvf terraform-cleaner_0.0.4_linux_amd64.tar.gz
      
      - name: Run Terraform Cleaner
        id: terraform-cleaner
        run: |
          mv terraform-cleaner /usr/local/bin 
          terraform-cleaner
          cleaner_output=$(terraform-cleaner 2>&1)
          echo "::set-output name=cleaner-output::$cleaner_output"

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ Token }}
          script: |
            const output = `Terraform Cleaner Output:\n\n${{ steps.terraform-cleaner.outputs['cleaner-output'] }}`;
            const { context } = github;
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            github.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: output,
            });
