name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  PULL_REQUEST_NUMBER: 1

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set pull request number
        run: echo "PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Run tfsec
        run: tfsec ./Learn_terrraform

      - name: Generate SARIF file
        run: tfsec --format=sarif ./Learn_terrraform > tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif

      - name: Comment on pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const sarifContent = fs.readFileSync('tfsec.sarif', 'utf8');
            const context = github.context;
            const repo = context.payload.repository;
            const pullRequestNumber = context.payload.pull_request.number;
            const comment = `#### tfsec Report for Pull Request ${pullRequestNumber}\n\n\`\`\`\n${sarifContent}\n\`\`\``;
            github.issues.createComment({
              owner: repo.owner.login,
              repo: repo.name,
              issue_number: pullRequestNumber,
              body: comment,
            });
